# Generated by Django 4.2 on 2025-11-11 13:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_app_de", models.CharField(max_length=255)),
                ("name_app_fr", models.CharField(max_length=255)),
                ("zusammenfassung_de", models.TextField()),
                ("zusammenfassung_fr", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Datenstand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datenstand", models.DateField(default=datetime.date(1900, 1, 1))),
            ],
            options={
                "verbose_name": "Datenstand",
                "verbose_name_plural": "Datenstände",
                "ordering": ["datenstand"],
            },
        ),
        migrations.CreateModel(
            name="Dienst",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technischer_name_dienst", models.CharField(max_length=255)),
                ("name_dienst_de", models.CharField(max_length=255)),
                ("name_dienst_fr", models.CharField(max_length=255)),
                ("zusammenfassung_de", models.TextField()),
                ("zusammenfassung_fr", models.TextField()),
                ("quellennachweis_de", models.TextField()),
                ("quellennachweis_fr", models.TextField()),
                ("extern", models.BooleanField()),
                (
                    "owner",
                    models.CharField(
                        choices=[("awn", "AWN"), ("agi", "AGI")], max_length=50
                    ),
                ),
            ],
            options={
                "verbose_name": "Dienst",
                "verbose_name_plural": "Dienste",
                "ordering": ["name_dienst_de"],
            },
        ),
        migrations.CreateModel(
            name="Ebene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("titel_de", models.CharField(max_length=200)),
                ("titel_fr", models.CharField(max_length=200)),
                ("kurzbeschreibung_de", models.TextField()),
                ("kurzbeschreibung_fr", models.TextField()),
                ("editierbar", models.BooleanField()),
                (
                    "featurekategorie",
                    models.CharField(
                        choices=[
                            ("Raster", "Raster"),
                            ("Vektor", "Vektor"),
                            ("Tabelle", "Tabelle"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "zugangsberechtigung",
                    models.CharField(
                        choices=[
                            ("A", "öffentlich zugängliche Geodaten"),
                            ("B", "beschränkt öffentlich zugängliche Geodaten"),
                            ("C", "nicht öffentlich zugängliche Geodaten"),
                        ],
                        max_length=1,
                    ),
                ),
                ("foerderprogramm", models.CharField(max_length=100)),
                ("dokumentation", models.TextField(blank=True, null=True)),
                ("bemerkungen", models.TextField(blank=True, null=True)),
                (
                    "datenstand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="editor.datenstand",
                    ),
                ),
                (
                    "dienst",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="editor.dienst",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ebene",
                "verbose_name_plural": "Ebenen",
                "ordering": ["titel_de"],
            },
        ),
        migrations.CreateModel(
            name="Geopaeckli",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(default="Unbenannt", max_length=200)),
                ("name_fr", models.CharField(default="Non nommé", max_length=200)),
                ("technischer_name", models.CharField(max_length=100, unique=True)),
                (
                    "nachfuehrungsintervall",
                    models.CharField(
                        choices=[
                            ("täglich", "täglich"),
                            ("wöchentlich", "wöchentlich"),
                            ("monatlich", "monatlich"),
                            ("quartalsweise", "quartalsweise"),
                            ("jährlich", "jährlich"),
                            ("bei Bedarf", "bei Bedarf"),
                            ("nie", "nie"),
                        ],
                        default="bitte wählen",
                        max_length=20,
                    ),
                ),
                ("dataowner", models.CharField(default="Unbekannt", max_length=200)),
                ("datasteward", models.CharField(default="Unbekannt", max_length=200)),
                ("dateneditor", models.CharField(default="Unbekannt", max_length=200)),
            ],
            options={
                "verbose_name": "Geopäckli",
                "verbose_name_plural": "Geopäckli",
                "ordering": ["name_de"],
            },
        ),
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=200)),
                ("name_fr", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Thema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technischer_name", models.CharField(max_length=200)),
                (
                    "beschreibung_de",
                    models.TextField(default="hier muss eine Beschreibung stehen"),
                ),
            ],
            options={
                "verbose_name": "Thema",
                "verbose_name_plural": "Themen",
                "ordering": ["technischer_name"],
            },
        ),
        migrations.CreateModel(
            name="Trigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="vollständiger Name", max_length=200),
                ),
                ("beschreibung_de", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Trigger",
                "verbose_name_plural": "Trigger",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Webmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Beschrieb")),
                (
                    "snippet",
                    models.TextField(verbose_name="Snippet (kurze Zusammenfassung)"),
                ),
                (
                    "culture",
                    models.CharField(
                        choices=[("DE", "Deutsch"), ("FR", "Französisch")],
                        default="DE",
                        max_length=2,
                        verbose_name="Sprache",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Zeitstand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zeitstand", models.CharField(default="1.1.1900", max_length=255)),
                (
                    "publikationsdatum",
                    models.DateField(default=datetime.date(1900, 1, 1)),
                ),
            ],
            options={
                "verbose_name": "Zeitstand",
                "verbose_name_plural": "Zeitstände",
                "ordering": ["publikationsdatum"],
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_workflow", models.CharField(max_length=255)),
                ("beschreibung_de", models.TextField()),
                (
                    "apps",
                    models.ManyToManyField(related_name="workflows", to="editor.app"),
                ),
            ],
            options={
                "verbose_name": "Workflow",
                "verbose_name_plural": "Workflows",
                "ordering": ["name_workflow"],
            },
        ),
        migrations.CreateModel(
            name="Wertetabelle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_tabelle", models.CharField(max_length=255)),
                ("kurzbeschreibung_de", models.TextField()),
                ("kurzbeschreibung_fr", models.TextField()),
                (
                    "ebene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="editor.ebene",
                    ),
                ),
                (
                    "geopaeckli",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="editor.geopaeckli",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wertetabelle",
                "verbose_name_plural": "Wertetabellen",
                "ordering": ["name_tabelle"],
            },
        ),
        migrations.CreateModel(
            name="View",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_view", models.CharField(max_length=255)),
                ("beschreibung_de", models.TextField()),
                (
                    "dienst",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="editor.dienst",
                    ),
                ),
            ],
            options={
                "verbose_name": "View",
                "verbose_name_plural": "Views",
                "ordering": ["name_view"],
            },
        ),
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_map_de", models.CharField(max_length=255)),
                ("name_map_fr", models.CharField(max_length=255)),
                ("zusammenfassung_de", models.TextField()),
                ("zusammenfassung_fr", models.TextField()),
                (
                    "dienste",
                    models.ManyToManyField(related_name="maps", to="editor.dienst"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Layergroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("layer", models.ManyToManyField(to="editor.layer")),
            ],
        ),
        migrations.AddField(
            model_name="geopaeckli",
            name="thema",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="geopaeckli",
                to="editor.thema",
            ),
        ),
        migrations.AddField(
            model_name="geopaeckli",
            name="zeitstand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="editor.zeitstand",
            ),
        ),
        migrations.AddField(
            model_name="ebene",
            name="geopaeckli",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="editor.geopaeckli"
            ),
        ),
        migrations.AddField(
            model_name="ebene",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="Ebene", to="editor.tag"
            ),
        ),
        migrations.AddField(
            model_name="ebene",
            name="triggers",
            field=models.ManyToManyField(
                blank=True, related_name="ebenen", to="editor.trigger"
            ),
        ),
        migrations.AddField(
            model_name="ebene",
            name="views",
            field=models.ManyToManyField(blank=True, to="editor.view"),
        ),
        migrations.AddField(
            model_name="dienst",
            name="wertetabellen",
            field=models.ManyToManyField(
                blank=True, related_name="dienste", to="editor.wertetabelle"
            ),
        ),
        migrations.CreateModel(
            name="Attribut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_attribut", models.CharField(max_length=255)),
                ("kurzbezeichnung_de", models.CharField(max_length=255)),
                ("kurzbezeichnung_fr", models.CharField(max_length=255)),
                ("beschreibung_de", models.TextField(blank=True, null=True)),
                (
                    "attributtyp",
                    models.CharField(
                        choices=[
                            ("int", "Ganzzahl"),
                            ("float", "Gleitkommazahl"),
                            ("date", "Datum"),
                            ("datetime", "Datum mit Uhrzeit"),
                            ("text", "Text"),
                            ("bool", "Boolean"),
                        ],
                        max_length=20,
                    ),
                ),
                ("attributlaenge", models.IntegerField()),
                ("pflicht", models.BooleanField()),
                ("unique", models.BooleanField()),
                ("index", models.BooleanField()),
                (
                    "ebene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute",
                        to="editor.ebene",
                    ),
                ),
                (
                    "wertetabelle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute",
                        to="editor.wertetabelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribut",
                "verbose_name_plural": "Attribute",
                "ordering": ["name_attribut"],
            },
        ),
        migrations.AddField(
            model_name="app",
            name="map",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="app",
                to="editor.map",
            ),
        ),
    ]
