# Generated by Django 4.2 on 2025-11-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0002_remove_zeitstand"),
    ]

    operations = [
        migrations.AddField(
            model_name="geopaeckli",
            name="zeitstand_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
