# Generated by Django 4.2.20 on 2025-03-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0003_remove_layer_layergroup_layergroup_layer"),
    ]

    operations = [
        migrations.AddField(
            model_name="layergroup",
            name="responsible_person",
            field=models.CharField(default="Hanskaspar Frei", max_length=100),
            preserve_default=False,
        ),
    ]
