# Generated by Django 4.2.20 on 2025-04-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0005_remove_layergroup_responsible_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Beschrieb")),
                (
                    "snippet",
                    models.TextField(verbose_name="Snippet (kurze Zusammenfassung)"),
                ),
                (
                    "culture",
                    models.CharField(
                        choices=[("DE", "Deutsch"), ("FR", "Französisch")],
                        default="DE",
                        max_length=2,
                        verbose_name="Sprache",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
