# Generated by Django 4.2 on 2025-11-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0006_remove_ebene_datenstand_fk_and_delete_datenstand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ebene",
            name="foerderprogramm",
            field=models.CharField(
                choices=[("NFA", "NFA"), ("Prosam", "Prosam"), ("Andere", "Andere")],
                default="Andere",
                max_length=100,
            ),
        ),
    ]
