# Generated by Django 4.2 on 2026-01-19 13:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0007_alter_ebene_foerderprogramm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geopaeckli",
            name="zeitstand_text",
        ),
        migrations.AlterField(
            model_name="ebene",
            name="datenstand_date",
            field=models.DateField(default=datetime.date(1900, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="geopaeckli",
            name="technischer_name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Technischer Name darf keine Leerzeichen enthalten und nur Buchstaben, Zahlen, Unterstrich oder Bindestrich.",
                        regex="^[A-Za-z0-9_-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="thema",
            name="technischer_name",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Technischer Name darf keine Leerzeichen enthalten und nur Buchstaben, Zahlen, Unterstrich oder Bindestrich.",
                        regex="^[A-Za-z0-9_-]+$",
                    )
                ],
            ),
        ),
    ]
