# Generated by Django 4.2 on 2026-01-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0008_remove_geopaeckli_zeitstand_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ebene",
            name="attributes_shared",
            field=models.ManyToManyField(
                blank=True, related_name="shared_in_ebenen", to="editor.attribut"
            ),
        ),
    ]
