# Generated by Copilot on 2026-02-18
from django.db import migrations, models
import django.db.models.deletion


def forwards_assign_geopaeckli(apps, schema_editor):
    Attribut = apps.get_model('editor', 'Attribut')
    Ebene = apps.get_model('editor', 'Ebene')
    # For each attribute, if it references an Ebene, copy that Ebene's geopaeckli
    for attr in Attribut.objects.all():
        ebene_id = getattr(attr, 'ebene_id', None)
        if ebene_id:
            try:
                eb = Ebene.objects.get(pk=ebene_id)
            except Ebene.DoesNotExist:
                continue
            geop = getattr(eb, 'geopaeckli_id', None)
            if geop:
                attr.geopaeckli_id = geop
                attr.save(update_fields=['geopaeckli'])


def reverse_unassign_geopaeckli(apps, schema_editor):
    Attribut = apps.get_model('editor', 'Attribut')
    # Revert by removing geopaeckli assignment
    Attribut.objects.update(geopaeckli=None)


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_alter_attribut_ebene_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribut',
            name='geopaeckli',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='attribute_geopaeckli',
                to='editor.geopaeckli',
                null=True,
                blank=True,
            ),
        ),
        migrations.RunPython(forwards_assign_geopaeckli, reverse_unassign_geopaeckli),
    ]
