# Generated by Copilot on 2026-02-18
"""No-op migration to preserve history while preventing removal of Attribut.ebene.

This replaces the previous remove-field migration so applying 0012 will not
alter the database schema. If you want to fully revert applied migrations,
run `python manage.py migrate editor 0011` in your project.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0011_add_geopaeckli_and_migrate"),
    ]

    operations = []
