# Generated by Django 4.2 on 2026-02-18 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0012_remove_ebene_from_attribut"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attribut",
            name="ebene",
        ),
        migrations.AlterField(
            model_name="wertetabelle",
            name="geopaeckli",
            field=models.ForeignKey(
                blank=True,
                db_column="geopaeckli_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="editor.geopaeckli",
            ),
        ),
    ]
