# Generated by Django 4.2 on 2026-03-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0013_add_geopaeckli_to_wertetabelle_and_migrate"),
        ("editor", "0013_remove_attribut_ebene_alter_wertetabelle_geopaeckli"),
        ("editor", "0015_populate_geopaeckli_from_ebene"),
    ]

    operations = []
