# Generated by Django 4.2 on 2026-03-13 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0016_merge_20260306_1047"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributV2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_attribut", models.CharField(max_length=255)),
                ("kurzbezeichnung_de", models.CharField(max_length=255)),
                ("kurzbezeichnung_fr", models.CharField(max_length=255)),
                ("beschreibung_de", models.TextField(blank=True, null=True)),
                (
                    "attributtyp",
                    models.CharField(
                        choices=[
                            ("int", "Ganzzahl"),
                            ("float", "Gleitkommazahl"),
                            ("date", "Datum"),
                            ("datetime", "Datum mit Uhrzeit"),
                            ("text", "Text"),
                            ("bool", "Boolean"),
                        ],
                        max_length=20,
                    ),
                ),
                ("attributlaenge", models.IntegerField()),
                ("pflicht", models.BooleanField()),
                ("unique", models.BooleanField()),
                ("index", models.BooleanField()),
                (
                    "geopaeckli",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="v2_attribute",
                        to="editor.geopaeckli",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribut V2",
                "verbose_name_plural": "Attribute V2",
                "ordering": ["name_attribut"],
            },
        ),
        migrations.AlterField(
            model_name="ebene",
            name="foerderprogramm",
            field=models.CharField(
                choices=[
                    ("NFA", "NFA"),
                    ("Kantonales Förderprogramm", "Kantonales Förderprogramm"),
                    ("ohne staatliche Förderung", "ohne staatliche Förderung"),
                    ("---", "---"),
                ],
                default="---",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="WertetabelleV2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_tabelle", models.CharField(max_length=255)),
                ("kurzbeschreibung_de", models.TextField()),
                ("kurzbeschreibung_fr", models.TextField()),
                (
                    "geopaeckli",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="v2_wertetabellen",
                        to="editor.geopaeckli",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wertetabelle V2",
                "verbose_name_plural": "Wertetabellen V2",
                "ordering": ["name_tabelle"],
            },
        ),
        migrations.CreateModel(
            name="EbeneV2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("titel_de", models.CharField(max_length=200)),
                ("titel_fr", models.CharField(max_length=200)),
                ("kurzbeschreibung_de", models.TextField()),
                ("kurzbeschreibung_fr", models.TextField()),
                ("editierbar", models.BooleanField()),
                (
                    "featurekategorie",
                    models.CharField(
                        choices=[
                            ("Raster", "Raster"),
                            ("Vektor", "Vektor"),
                            ("Tabelle", "Tabelle"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "zugangsberechtigung",
                    models.CharField(
                        choices=[
                            ("A", "öffentlich zugängliche Geodaten"),
                            ("B", "beschränkt öffentlich zugängliche Geodaten"),
                            ("C", "nicht öffentlich zugängliche Geodaten"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "foerderprogramm",
                    models.CharField(
                        choices=[
                            ("NFA", "NFA"),
                            ("Kantonales Förderprogramm", "Kantonales Förderprogramm"),
                            ("ohne staatliche Förderung", "ohne staatliche Förderung"),
                            ("---", "---"),
                        ],
                        default="---",
                        max_length=100,
                    ),
                ),
                ("dokumentation", models.TextField(blank=True, null=True)),
                ("datenstand_date", models.DateField()),
                (
                    "attribute",
                    models.ManyToManyField(
                        blank=True, related_name="v2_ebenen", to="editor.attributv2"
                    ),
                ),
                (
                    "dienst",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="v2_ebenen",
                        to="editor.dienst",
                    ),
                ),
                (
                    "geopaeckli",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="v2_ebenen",
                        to="editor.geopaeckli",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="v2_ebenen", to="editor.tag"
                    ),
                ),
                (
                    "triggers",
                    models.ManyToManyField(
                        blank=True, related_name="v2_ebenen", to="editor.trigger"
                    ),
                ),
                (
                    "views",
                    models.ManyToManyField(
                        blank=True, related_name="v2_ebenen", to="editor.view"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ebene V2",
                "verbose_name_plural": "Ebenen V2",
                "ordering": ["titel_de"],
            },
        ),
        migrations.AddField(
            model_name="attributv2",
            name="wertetabellen",
            field=models.ManyToManyField(
                blank=True, related_name="v2_attribute", to="editor.wertetabellev2"
            ),
        ),
    ]
