# Generated by Django 4.2 on 2026-03-25 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0017_attributv2_alter_ebene_foerderprogramm_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ebenev2",
            name="attribute",
        ),
        migrations.RemoveField(
            model_name="ebenev2",
            name="dienst",
        ),
        migrations.RemoveField(
            model_name="ebenev2",
            name="geopaeckli",
        ),
        migrations.RemoveField(
            model_name="ebenev2",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="ebenev2",
            name="triggers",
        ),
        migrations.RemoveField(
            model_name="ebenev2",
            name="views",
        ),
        migrations.RemoveField(
            model_name="wertetabellev2",
            name="geopaeckli",
        ),
        migrations.RemoveField(
            model_name="attribut",
            name="wertetabelle",
        ),
        migrations.RemoveField(
            model_name="dienst",
            name="wertetabellen",
        ),
        migrations.RemoveField(
            model_name="ebene",
            name="attributes_shared",
        ),
        migrations.RemoveField(
            model_name="wertetabelle",
            name="ebene",
        ),
        migrations.AddField(
            model_name="attribut",
            name="wertetabellen",
            field=models.ManyToManyField(
                blank=True, related_name="attribute", to="editor.wertetabelle"
            ),
        ),
        migrations.AddField(
            model_name="ebene",
            name="attribute",
            field=models.ManyToManyField(
                blank=True, related_name="ebenen", to="editor.attribut"
            ),
        ),
        migrations.AlterField(
            model_name="attribut",
            name="geopaeckli",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attribute",
                to="editor.geopaeckli",
            ),
        ),
        migrations.AlterField(
            model_name="ebene",
            name="dienst",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ebenen",
                to="editor.dienst",
            ),
        ),
        migrations.AlterField(
            model_name="ebene",
            name="geopaeckli",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ebenen",
                to="editor.geopaeckli",
            ),
        ),
        migrations.AlterField(
            model_name="ebene",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="ebenen", to="editor.tag"
            ),
        ),
        migrations.AlterField(
            model_name="ebene",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="ebenen", to="editor.view"
            ),
        ),
        migrations.AlterField(
            model_name="geopaeckli",
            name="nachfuehrungsintervall",
            field=models.CharField(
                choices=[
                    ("täglich", "täglich"),
                    ("wöchentlich", "wöchentlich"),
                    ("monatlich", "monatlich"),
                    ("quartalsweise", "quartalsweise"),
                    ("jährlich", "jährlich"),
                    ("bei Bedarf", "bei Bedarf"),
                    ("nie", "nie"),
                ],
                default="bei Bedarf",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="geopaeckli",
            name="technischer_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="thema",
            name="beschreibung_de",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="thema",
            name="technischer_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="wertetabelle",
            name="geopaeckli",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wertetabellen",
                to="editor.geopaeckli",
            ),
        ),
        migrations.DeleteModel(
            name="AttributV2",
        ),
        migrations.DeleteModel(
            name="EbeneV2",
        ),
        migrations.DeleteModel(
            name="WertetabelleV2",
        ),
    ]
