# Generated by Django 6.0.3 on 2026-03-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0018_remove_ebenev2_attribute_remove_ebenev2_dienst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layergroup',
            name='layer',
        ),
        migrations.DeleteModel(
            name='Webmap',
        ),
        migrations.DeleteModel(
            name='Layer',
        ),
        migrations.DeleteModel(
            name='Layergroup',
        ),
    ]
