# Generated by Django 4.2.20 on 2025-03-26 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layergroup",
            name="layers",
        ),
        migrations.AddField(
            model_name="layer",
            name="layergroup",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="editor.layergroup",
            ),
        ),
    ]
