# Generated by Django 4.2.20 on 2025-03-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0002_remove_layergroup_layers_layer_layergroup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layer",
            name="layergroup",
        ),
        migrations.AddField(
            model_name="layergroup",
            name="layer",
            field=models.ManyToManyField(to="editor.layer"),
        ),
    ]
