# Generated by Django 4.2.20 on 2025-03-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0004_layergroup_responsible_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layergroup",
            name="responsible_person",
        ),
    ]
