# Generated by Django 5.2 on 2025-06-30 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0006_webmap"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ebene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("titel_de", models.CharField(max_length=200)),
                ("titel_fr", models.CharField(max_length=200)),
                ("kurzbeschreibung_de", models.TextField()),
                ("kurzbeschreibung_fr", models.TextField()),
                ("editierbar", models.BooleanField()),
                (
                    "featurekategorie",
                    models.CharField(
                        choices=[
                            ("Raster", "Raster"),
                            ("Vektor", "Vektor"),
                            ("Tabelle", "Tabelle"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "zugangsberechtigung",
                    models.CharField(
                        choices=[
                            ("A", "öffentlich zugängliche Geodaten"),
                            ("B", "beschränkt öffentlich zugängliche Geodaten"),
                            ("C", "nicht öffentlich zugängliche Geodaten"),
                        ],
                        max_length=1,
                    ),
                ),
                ("foerderprogramm", models.CharField(max_length=100)),
                ("dokumentation", models.URLField(blank=True, null=True)),
                ("bemerkungen", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Thema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technischer_name", models.CharField(max_length=200)),
                ("beschreibung_de", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Wertetabelle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_tabelle", models.CharField(max_length=255)),
                ("kurzbeschreibung_de", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Dienst",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technischer_name_dienst", models.CharField(max_length=255)),
                ("name_dienst_de", models.CharField(max_length=255)),
                ("name_dienst_fr", models.CharField(max_length=255)),
                ("zusammenfassung_de", models.TextField()),
                ("zusammenfassung_fr", models.TextField()),
                ("quellennachweis_de", models.TextField()),
                ("quellennachweis_fr", models.TextField()),
                ("extern", models.BooleanField()),
                ("owner", models.CharField(max_length=255)),
                (
                    "ebenen",
                    models.ManyToManyField(related_name="dienste", to="editor.ebene"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Datenstand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datenstand", models.CharField(max_length=255)),
                (
                    "ebene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datenstaende",
                        to="editor.ebene",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Geopaeckli",
            fields=[
                (
                    "technischer_name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name_de", models.CharField(max_length=200)),
                ("name_fr", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "nachfuehrungsintervall",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("täglich", "täglich"),
                            ("wöchentlich", "wöchentlich"),
                            ("monatlich", "monatlich"),
                            ("quartalsweise", "quartalsweise"),
                            ("jährlich", "jährlich"),
                            ("bei Bedarf", "bei Bedarf"),
                            ("nie", "nie"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("dataowner", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "datasteward",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dateneditor",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "datenstand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="editor.datenstand",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ebene",
            name="geopaeckli",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="editor.geopaeckli"
            ),
        ),
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_map_de", models.CharField(max_length=255)),
                ("name_map_fr", models.CharField(max_length=255)),
                ("zusammenfassung_de", models.TextField()),
                ("zusammenfassung_fr", models.TextField()),
                (
                    "dienste",
                    models.ManyToManyField(related_name="maps", to="editor.dienst"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_map_de", models.CharField(max_length=255)),
                ("name_map_fr", models.CharField(max_length=255)),
                ("zusammenfassung_de", models.TextField()),
                ("zusammenfassung_fr", models.TextField()),
                (
                    "map",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app",
                        to="editor.map",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_de", models.CharField(max_length=200)),
                ("name_fr", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ebenen", models.ManyToManyField(blank=True, to="editor.ebene")),
            ],
        ),
        migrations.AddField(
            model_name="geopaeckli",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="geopaeckli", to="editor.tag"
            ),
        ),
        migrations.AddField(
            model_name="geopaeckli",
            name="thema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="geopaeckli",
                to="editor.thema",
            ),
        ),
        migrations.CreateModel(
            name="View",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_view", models.CharField(max_length=255)),
                ("beschreibung_de", models.TextField()),
                (
                    "ebenen",
                    models.ManyToManyField(related_name="views", to="editor.ebene"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dienst",
            name="views",
            field=models.ManyToManyField(related_name="dienste", to="editor.view"),
        ),
        migrations.AddField(
            model_name="dienst",
            name="wertetabellen",
            field=models.ManyToManyField(
                blank=True, related_name="dienste", to="editor.wertetabelle"
            ),
        ),
        migrations.CreateModel(
            name="Attribut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_attribut", models.CharField(max_length=255)),
                ("kurzbezeichnung_de", models.CharField(max_length=255)),
                ("kurzbezeichnung_fr", models.CharField(max_length=255)),
                ("beschreibung_de", models.TextField(blank=True, null=True)),
                ("attributtyp", models.CharField(max_length=255)),
                ("attributlaenge", models.IntegerField()),
                ("pflicht", models.BooleanField()),
                ("unique", models.BooleanField()),
                ("index", models.BooleanField()),
                (
                    "ebene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute",
                        to="editor.ebene",
                    ),
                ),
                (
                    "wertetabelle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute",
                        to="editor.wertetabelle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_workflow", models.CharField(max_length=255)),
                ("beschreibung_de", models.TextField()),
                (
                    "apps",
                    models.ManyToManyField(related_name="workflows", to="editor.app"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Zeitstand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zeitstand", models.CharField(max_length=255)),
                ("publikationsdatum", models.DateField()),
                (
                    "geopaeckli",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zeitstaende",
                        to="editor.geopaeckli",
                    ),
                ),
            ],
        ),
    ]
