# Generated by Django 4.2 on 2025-07-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0007_ebene_thema_wertetabelle_dienst_datenstand_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attribut",
            options={
                "ordering": ["name_attribut"],
                "verbose_name": "Attribut",
                "verbose_name_plural": "Attribute",
            },
        ),
        migrations.AlterModelOptions(
            name="datenstand",
            options={
                "ordering": ["datenstand"],
                "verbose_name": "Datenstand",
                "verbose_name_plural": "Datenstände",
            },
        ),
        migrations.AlterModelOptions(
            name="dienst",
            options={
                "ordering": ["name_dienst_de"],
                "verbose_name": "Dienst",
                "verbose_name_plural": "Dienste",
            },
        ),
        migrations.AlterModelOptions(
            name="ebene",
            options={
                "ordering": ["titel_de"],
                "verbose_name": "Ebene",
                "verbose_name_plural": "Ebenen",
            },
        ),
        migrations.AlterModelOptions(
            name="geopaeckli",
            options={
                "ordering": ["name_de"],
                "verbose_name": "Geopäckli",
                "verbose_name_plural": "Geopäckli",
            },
        ),
        migrations.AlterModelOptions(
            name="thema",
            options={
                "ordering": ["technischer_name"],
                "verbose_name": "Thema",
                "verbose_name_plural": "Themen",
            },
        ),
        migrations.AlterModelOptions(
            name="view",
            options={
                "ordering": ["name_view"],
                "verbose_name": "View",
                "verbose_name_plural": "Views",
            },
        ),
        migrations.AlterModelOptions(
            name="wertetabelle",
            options={
                "ordering": ["name_tabelle"],
                "verbose_name": "Wertetabelle",
                "verbose_name_plural": "Wertetabellen",
            },
        ),
        migrations.AlterModelOptions(
            name="workflow",
            options={
                "ordering": ["name_workflow"],
                "verbose_name": "Workflow",
                "verbose_name_plural": "Workflows",
            },
        ),
        migrations.AlterModelOptions(
            name="zeitstand",
            options={
                "ordering": ["-publikationsdatum"],
                "verbose_name": "Zeitstand",
                "verbose_name_plural": "Zeitstände",
            },
        ),
    ]
