# Generated by Django 4.2 on 2025-07-30 07:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0008_alter_attribut_options_alter_datenstand_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datenstand",
            name="ebene",
        ),
        migrations.RemoveField(
            model_name="geopaeckli",
            name="datenstand",
        ),
        migrations.RemoveField(
            model_name="zeitstand",
            name="geopaeckli",
        ),
        migrations.AddField(
            model_name="geopaeckli",
            name="zeitstand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="editor.zeitstand",
            ),
        ),
        migrations.AlterField(
            model_name="datenstand",
            name="datenstand",
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AlterField(
            model_name="zeitstand",
            name="publikationsdatum",
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AlterField(
            model_name="zeitstand",
            name="zeitstand",
            field=models.CharField(default="1.1.1900", max_length=255),
        ),
    ]
