# Generated by Django 4.2 on 2025-08-06 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "editor",
            "0009_remove_datenstand_ebene_remove_geopaeckli_datenstand_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ebene",
            name="datenstand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="editor.datenstand",
            ),
        ),
        migrations.AddField(
            model_name="ebene",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="Ebene", to="editor.tag"
            ),
        ),
    ]
