# Generated by Django 4.2 on 2025-08-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0010_ebene_datenstand_ebene_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geopaeckli",
            name="tags",
        ),
    ]
