# Generated by Django 4.2 on 2025-09-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0011_remove_geopaeckli_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vollstaendiger_name", models.CharField(max_length=200)),
                ("beschreibung_de", models.TextField()),
            ],
            options={
                "verbose_name": "Trigger",
                "verbose_name_plural": "Trigger",
                "ordering": ["vollstaendiger_name"],
            },
        ),
        migrations.RemoveField(
            model_name="thema",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="thema",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="attribut",
            name="attributtyp",
            field=models.CharField(
                choices=[("int", "Integer"), ("float", "Float"), ("str", "String")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dienst",
            name="ebenen",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="dienste", to="editor.ebene"
            ),
        ),
        migrations.AlterField(
            model_name="dienst",
            name="views",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="dienste", to="editor.view"
            ),
        ),
        migrations.AlterField(
            model_name="ebene",
            name="dokumentation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="geopaeckli",
            name="dataowner",
            field=models.CharField(default="Unbekannt", max_length=200),
        ),
        migrations.AlterField(
            model_name="geopaeckli",
            name="datasteward",
            field=models.CharField(default="Unbekannt", max_length=200),
        ),
        migrations.AlterField(
            model_name="geopaeckli",
            name="dateneditor",
            field=models.CharField(default="Unbekannt", max_length=200),
        ),
        migrations.AlterField(
            model_name="geopaeckli",
            name="nachfuehrungsintervall",
            field=models.CharField(
                choices=[
                    ("täglich", "täglich"),
                    ("wöchentlich", "wöchentlich"),
                    ("monatlich", "monatlich"),
                    ("quartalsweise", "quartalsweise"),
                    ("jährlich", "jährlich"),
                    ("bei Bedarf", "bei Bedarf"),
                    ("nie", "nie"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="geopaeckli",
            name="name_de",
            field=models.CharField(default="Unbenannt", max_length=200),
        ),
        migrations.AlterField(
            model_name="geopaeckli",
            name="name_fr",
            field=models.CharField(default="Non nommé", max_length=200),
        ),
        migrations.AlterField(
            model_name="geopaeckli",
            name="thema",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="geopaeckli",
                to="editor.thema",
            ),
        ),
        migrations.AlterField(
            model_name="geopaeckli",
            name="zeitstand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="editor.zeitstand",
            ),
        ),
        migrations.AlterField(
            model_name="thema",
            name="beschreibung_de",
            field=models.TextField(default="hier muss eine Beschreibung stehen"),
        ),
        migrations.AddField(
            model_name="ebene",
            name="triggers",
            field=models.ManyToManyField(
                blank=True, related_name="ebenen", to="editor.trigger"
            ),
        ),
    ]
