# Generated by Django 4.2 on 2025-09-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0012_trigger_remove_thema_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trigger",
            options={
                "ordering": ["name"],
                "verbose_name": "Trigger",
                "verbose_name_plural": "Trigger",
            },
        ),
        migrations.RemoveField(
            model_name="trigger",
            name="vollstaendiger_name",
        ),
        migrations.AddField(
            model_name="trigger",
            name="name",
            field=models.CharField(default="vollständiger Name", max_length=200),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="beschreibung_de",
            field=models.TextField(blank=True, null=True),
        ),
    ]
