# Generated by Django 4.2 on 2025-09-09 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0013_alter_trigger_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zeitstand",
            options={
                "ordering": ["publikationsdatum"],
                "verbose_name": "Zeitstand",
                "verbose_name_plural": "Zeitstände",
            },
        ),
        migrations.RemoveField(
            model_name="geopaeckli",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="geopaeckli",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="view",
            name="ebenen",
        ),
        migrations.AddField(
            model_name="ebene",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="ebenen", to="editor.view"
            ),
        ),
        migrations.AddField(
            model_name="wertetabelle",
            name="geopaeckli",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="editor.geopaeckli",
            ),
        ),
        migrations.AlterField(
            model_name="attribut",
            name="beschreibung_de",
            field=models.TextField(default="hier muss eine Beschreibung stehen"),
        ),
        migrations.AlterField(
            model_name="geopaeckli",
            name="nachfuehrungsintervall",
            field=models.CharField(
                choices=[
                    ("täglich", "täglich"),
                    ("wöchentlich", "wöchentlich"),
                    ("monatlich", "monatlich"),
                    ("quartalsweise", "quartalsweise"),
                    ("jährlich", "jährlich"),
                    ("bei Bedarf", "bei Bedarf"),
                    ("nie", "nie"),
                ],
                default="bitte wählen",
                max_length=20,
            ),
        ),
    ]
