# Generated by Django 4.2 on 2025-09-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "editor",
            "0014_alter_zeitstand_options_remove_geopaeckli_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="wertetabelle",
            name="kurzbeschreibung_fr",
            field=models.TextField(default="Describtion"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attribut",
            name="beschreibung_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dienst",
            name="ebenen",
            field=models.ManyToManyField(
                blank=True, related_name="dienste", to="editor.ebene"
            ),
        ),
        migrations.AlterField(
            model_name="dienst",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="dienste", to="editor.view"
            ),
        ),
    ]
