# Generated by Django 4.2 on 2025-09-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0015_wertetabelle_kurzbeschreibung_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wertetabelle",
            name="ebene",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="editor.ebene",
            ),
        ),
    ]
