# Generated by Django 4.2 on 2025-09-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0016_wertetabelle_ebene"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dienst",
            name="views",
        ),
        migrations.AddField(
            model_name="view",
            name="dienst",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="editor.dienst",
            ),
        ),
        migrations.AlterField(
            model_name="attribut",
            name="attributtyp",
            field=models.CharField(
                choices=[
                    ("int", "Ganzzahl"),
                    ("float", "Gleitkommazahl"),
                    ("date", "Datum"),
                    ("datetime", "Datum mit Uhrzeit"),
                    ("text", "Text"),
                    ("bool", "Boolean"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dienst",
            name="owner",
            field=models.CharField(
                choices=[("awn", "AWN"), ("agi", "AGI")], max_length=50
            ),
        ),
    ]
