# Generated by Django 4.2 on 2025-09-12 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0017_remove_dienst_views_view_dienst_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="app",
            old_name="name_map_de",
            new_name="name_app_de",
        ),
        migrations.RenameField(
            model_name="app",
            old_name="name_map_fr",
            new_name="name_app_fr",
        ),
        migrations.RemoveField(
            model_name="ebene",
            name="views",
        ),
        migrations.AddField(
            model_name="ebene",
            name="dienst",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="editor.dienst",
            ),
        ),
    ]
