# Generated by Django 4.2 on 2025-09-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0018_rename_name_map_de_app_name_app_de_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="ebenen",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="ebene",
            name="views",
            field=models.ManyToManyField(blank=True, to="editor.view"),
        ),
    ]
