# Generated by Django 4.2 on 2025-09-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0019_remove_tag_created_at_remove_tag_ebenen_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dienst",
            name="ebenen",
        ),
    ]
